# Generated by Django 2.2.5 on 2019-09-06 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeMusica', models.CharField(max_length=255, verbose_name='nomeMusica')),
                ('artista', models.CharField(max_length=255, verbose_name='genero')),
                ('link', models.CharField(max_length=255, verbose_name='link')),
            ],
        ),
    ]
