# Generated by Django 2.2.5 on 2019-09-06 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musica',
            name='genero',
            field=models.CharField(default=1, max_length=255, verbose_name='genero'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='musica',
            name='artista',
            field=models.CharField(max_length=255, verbose_name='artista'),
        ),
    ]
